FROM maven:3.8.4-openjdk-17-slim

# Set working directory
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code
#COPY src ./src

# Expose port for development
EXPOSE 8080

# Run Maven with hot reload (spring-boot-devtools)
CMD ["mvn", "spring-boot:run","-Dspring-boot.run.arguments=--spring.devtools.restart.enabled=true"]
