server {
    listen 80;

    # If the Nginx can't find a file, just serve index.html, 
    # then React router will handle it.
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
